name: Build JAM.exe with MSVC

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build with MSVC
      shell: cmd
      run: cl /O2 /EHsc jam\main.cpp /Fe:jam.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: jam.exe
        path: jam.exe
        retention-days: 5
